[package]
name = "skyrim_alchemy_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyrim_alchemy_db = { path="../skyrim_alchemy_db" }
wasm-bindgen = "0.2"
web-sys = {version="0.3", features=["console"] }
js-sys = "0.3"